### ISSUE TITLE
모바일 버전 분리

### ISSUE THREAD

**Issue by dodo4114** [Island-dev/Island-dev.github.io#19]
- [x] width 기준으로 디자인 변경
- [x] 모바일 인식해서 특수 변경 사항 적용

**Comment by mh960110** [comment]
이게 생각보다 힘들지도..

**Comment by mh960110** [comment]
@ddal0115 모바일 페이지 스크롤 할 때 위 아래가 사라지면서 height가 증가하는데 따라서 vh, vmin, vmax 단위보다는 vw 단위를 사용하는 게 좋음!

**Comment by ddal0115** [comment]
넹 알겠습니다!
