### ISSUE TITLE
css 적용하기

### ISSUE THREAD

**Issue by dodo4114** [Island-dev/Island-dev.github.io#2]
제플린을 통해 디자인이 넘어온 후, css 작업을 시작해야 합니다.

이 작업은 디자이너가 직접하면 좋을 것 같습니다.
혜민이도 의사가 있는 것 같아 css작업은 직접 하게 하려고 합니다.
이 때 혹시 고려해야 할 점이나 주의해야 할 점이 있다면 알려주세요.

**Comment by mh960110** [comment]
좋은 생각인 것 같아요

**Comment by Byeongjee** [comment]
이건아직 작업이 안된건가요? @dodo4114
