### ISSUE TITLE
Wrong position of store links

### ISSUE THREAD

**Issue by Byeongjee** [Island-dev/Island-dev.github.io#62]
![Capture](https://user-images.githubusercontent.com/24953444/94331295-4f968380-0006-11eb-8d5d-0847cbc24dc2.PNG)

이미 알고있겠지만 혹시나해서..

**Comment by ddal0115** [comment]
엥 저거 최신 파일 맞아?

![캡처](https://user-images.githubusercontent.com/63489074/94398303-42ad9780-01a0-11eb-8148-d605ae138960.JPG)

모바일 css는 아직 안 건드려서 엇갈리는게 맞고
사진처럼 안 떠?

**Comment by Byeongjee** [comment]
업데이트 되기 전 코드 기준으로 봐서 저렇게 나왔나봐. 다시 확인하니 잘 나와. 미안
