### ISSUE TITLE
Apply Favicon

### ISSUE THREAD

**Issue by Byeongjee** [Island-dev/Island-dev.github.io#68]
<img width="176" alt="시그널 홈페이지" src="https://user-images.githubusercontent.com/24953444/94433491-5cb49d80-01d3-11eb-9df3-48286c04f987.png">
이게 이미지를 이걸로 설정한건지, favicon을 빼먹은건지, 아님 설정했는데 버그가 있어서 저렇게 나오는건지 모르겠네요.
확인해주실수 있으신가요?

**Comment by ddal0115** [comment]
앗.. 아마 파비콘 아직 안 넣었을 거예요. 낼 파비콘 만들어서 추가하겠습니당
